amsdk-07.00.00.00.00-config: Add meta-qt5 layer
* Meta-qt5 is now required to avoid the parse error below.

ERROR: ParseError at
meta-arago/meta-arago-distro/recipes-qt/qt5/nativesdk-qtbase_5.1.1.bb:1:
Could not include required file recipes-qt/qt5/qt5-5.1.1.inc

Signed-off-by: Franklin S. Cooper Jr <fcooper@ti.com>