config: dunfell: fix the oe-core version to last working
The latest update in oe-core (meta) is causing build error in
dma-heap-test

Error:
CMakeFiles/dma-heap-unit-tests.dir/src/heap_test_fixture.cpp.o:
(.rodata._ZTI16HeapAllHeapsTest[_ZTI16HeapAllHeapsTest]+0x18):
undefined reference to `typeinfo for testing::Test

Signed-off-by: Yogesh Siraswar <yogeshs@ti.com>